name: Create GitHub Release

on:
  push:
    branches:
      - main   # adjust if your default branch is different

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read mod name and version from info.json
        id: mod_info
        run: |
          MOD_NAME=$(jq -r .name info.json)
          MOD_VERSION=$(jq -r .version info.json)
          echo "MOD_NAME=$MOD_NAME" >> $GITHUB_ENV
          echo "MOD_VERSION=$MOD_VERSION" >> $GITHUB_ENV

      - name: Create git tag
        run: |
          TAG="v${{ env.MOD_VERSION }}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "$TAG"
          git push origin "$TAG"

      - name: Create release directory
        run: mkdir -p "${{ env.MOD_NAME }}_${{ env.MOD_VERSION }}"

      - name: Copy mod files
        run: |
          cp data.lua info.json changelog.txt thumbnail.png "${{ env.MOD_NAME }}_${{ env.MOD_VERSION }}/"
          cp -r locale "${{ env.MOD_NAME }}_${{ env.MOD_VERSION }}/"

      - name: Zip Release
        run: |
          zip -r "${{ env.MOD_NAME }}_${{ env.MOD_VERSION }}.zip" "${{ env.MOD_NAME }}_${{ env.MOD_VERSION }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: "Release ${{ env.TAG }}"
          files: |
            ${{ env.MOD_NAME }}_${{ env.MOD_VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
