name: Package and Release Factorio Mod

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'  # Optional: trigger on version tags too

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Read mod name and version from info.json
        id: modinfo
        run: |
          MOD_NAME=$(jq -r .name info.json)
          MOD_VERSION=$(jq -r .version info.json)
          MOD_FOLDER="${MOD_NAME}_${MOD_VERSION}"
          echo "mod_name=$MOD_NAME" >> $GITHUB_OUTPUT
          echo "mod_version=$MOD_VERSION" >> $GITHUB_OUTPUT
          echo "mod_folder=$MOD_FOLDER" >> $GITHUB_OUTPUT

      - name: Prepare mod zip structure
        run: |
          mkdir -p "${{ steps.modinfo.outputs.mod_folder }}"
          shopt -s extglob
          cp -r !(.*|.git|.github) "${{ steps.modinfo.outputs.mod_folder }}/"
          zip -r "${{ steps.modinfo.outputs.mod_folder }}.zip" "${{ steps.modinfo.outputs.mod_folder }}"

      - name: Upload zip as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.modinfo.outputs.mod_folder }}
          path: ${{ steps.modinfo.outputs.mod_folder }}.zip

      - name: Create GitHub Release and upload zip
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.modinfo.outputs.mod_version }}
          tag_name: v${{ steps.modinfo.outputs.mod_version }}
          files: ${{ steps.modinfo.outputs.mod_folder }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
