name: Create Release Zip

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read mod name and version from info.json
        id: mod_info
        run: |
          MOD_NAME=$(jq -r .name info.json)
          MOD_VERSION=$(jq -r .version info.json)
          echo "MOD_NAME=$MOD_NAME" >> $GITHUB_ENV
          echo "MOD_VERSION=$MOD_VERSION" >> $GITHUB_ENV

      - name: Create release directory
        run: mkdir -p ${{ env.MOD_NAME }}_${{ env.MOD_VERSION }}

      - name: Copy mod files
        run: |
          cp data.lua info.json changelog.txt thumbnail.png ${{ env.MOD_NAME }}_${{ env.MOD_VERSION }}/
          cp -r locale ${{ env.MOD_NAME }}_${{ env.MOD_VERSION }}/

      - name: Zip Release
        run: |
          zip -r ${{ env.MOD_NAME }}_${{ env.MOD_VERSION }}.zip ${{ env.MOD_NAME }}_${{ env.MOD_VERSION }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.MOD_NAME }}_${{ env.MOD_VERSION }}
          path: ${{ env.MOD_NAME }}_${{ env.MOD_VERSION }}.zip
